import nodemailer from "nodemailer";

const sendAlertMail = async (to, imageUrl) => {
  try {
    const trasnpoter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.MAIL_USER,
        pass: process.env.MAIL_PASS,
      },
    });

    const mailoptions = {
      from: `"Night security Alerts" <${process.env.MAIL_USER}>`,
      to,
      subject: "Security Alert - New Image captured",

      html: `
           <div style="font-family: Arial, sans-serif; background-color: #f4f6f8; padding: 20px; border-radius: 8px;">
          <h2 style="color: #d32f2f; text-align: center;">🚨 Motion Detected!</h2>
          <p style="color: #333;">Hello,</p>
          <p style="color: #333;">
            Your Night Security System has detected motion and captured an image.
            Please review it immediately to ensure everything is safe.
          </p>
          <p style="color: #333;">
            You can click the button below to view the captured image:
          </p>

          <div style="text-align: center; margin: 20px 0;">
            <a href="${imageUrl}" target="_blank"
              style="background-color: #1976d2; color: white; padding: 10px 18px; text-decoration: none; border-radius: 6px; font-weight: bold;">
              🔍 View Captured Image
            </a>
          </div>

          <div style="text-align: center; margin-top: 10px;">
            <img src="${imageUrl}" alt="Captured Image"
              style="max-width: 100%; border-radius: 8px; border: 1px solid #ccc;" />
          </div>

          <hr style="margin: 25px 0; border: 0; border-top: 1px solid #ddd;" />

          <p style="font-size: 14px; color: #555;">
            ⚠️ This email was automatically generated by your Night Security System.
            <br/>Please do <strong>not reply</strong> to this email.
            <br/>If you keep receiving multiple alerts, check your system configuration.
          </p>

          <p style="text-align: center; font-size: 13px; color: #999;">
            © ${new Date().getFullYear()} Night Security System. All rights reserved.
          </p>
        </div>
        `,
    };

    await trasnpoter.sendMail(mailoptions);
    console.log(`Alert email sent to ${to}`);
  } catch (error) {
    console.log("Failed to send alert email:", error);
  }
};

export { sendAlertMail };
